"""
Django settings for T project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import time
# SIMPLEUI_CONFIG = {
#     'system_keep': False,
#     'menu_display': ['Simpleui', '测试', '权限认证', '动态菜单测试'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
#     'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
#     'menus': [{
#         'name': 'Simpleui',
#         'icon': 'fas fa-code',
#         'url': 'https://gitee.com/tompeppa/simpleui'
#     }, {
#         'app': 'auth',
#         'name': '权限认证',
#         'icon': 'fas fa-user-shield',
#         'models': [{
#             'name': '用户',
#             'icon': 'fa fa-user',
#             'url': 'auth/user/'
#         }]
#     }, {
#         'name': '测试',
#         'icon': 'fa fa-file',
#         'models': [{
#             'name': 'Baidu',
#             'url': 'http://baidu.com',
#             'icon': 'far fa-surprise'
#         }, {
#             'name': '内网穿透',
#             'url': 'https://www.wezoz.com',
#             'icon': 'fab fa-github'
#         }]
#     }, {
#         'name': '动态菜单测试' ,
#         'icon': 'fa fa-desktop',
#         'models': [{
#             'name': time.time(),
#             'url': 'http://baidu.com',
#             'icon': 'far fa-surprise'
#         }]
#     }]
# }

SIMPLEUI_STATIC_OFFLINE = True

SIMPLEUI_HOME_TITLE = '约健后台管理系统'

SIMPLEUI_HOME_INFO = False

# 首页显示最近动作
SIMPLEUI_HOME_ACTION = True

SIMPLEUI_CONFIG = {
    # 在自定义菜单的基础上保留系统模块
    'dynamic': True,
    # 'system_keep': True,
    'system_keep': False,
    'menus': [
        {
            'app': 'Tapp',
            'name': '用户管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/Tapp/user'
        },
        {
            'app': 'Tapp',
            'name': '俱乐部用户管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/Tapp/cadmin'
        },
        # {
        #     'app': 'activity',
        #     'name': '活动管理',
        #     'icon': 'fas fa-user-shield',
        #     'models': [{
        #         'name': '活动基本信息管理',
        #         'icon': 'fa fa-user',
        #         'url': '/admin/activity/activity'
        #     }

        #     ]
        # },
        {
            'app': 'club',
            'name': '俱乐部管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/club/club'
        },
        {
            'app': 'club',
            'name': '关注管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/club/attention'
        },
        {
            'app': 'coach',
            'name': '教练管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/coach/coach'
        },
        #    {
        #     'app': 'master',
        #     'name': '大师管理',
        #     'icon': 'fas fa-user-shield',
        #     'url':'/admin/master/master'
        # },
        {
            'app': 'activity',
            'name': '活动管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/activity/activity'
        },
        {
            'app': 'train',
            'name': '培训管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/train/train'
        },
        {
            'app': 'activity',
            'name': '报名管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/activity/apply'
        },

        {
            'app': 'auth',
            'name': '比赛管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/contest/contest'
        },

        {
            'app': 'video',
            'name': '视频管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/video/video'
        },

        # {
        #     'app': 'train',
        #     'name': '培训管理',
        #     'icon': 'fas fa-user-shield',
        #     'models': [{
        #         'name': '培训基本信息管理',
        #         'icon': 'fa fa-user',
        #         'url': '/admin/train/train'
        #     }]
        # },

        {
            'app': 'course',
            'name': '课程管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/course/course'
        },
        {
            'app': 'blueprint',
            'name': '晒图管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/blueprint/blueprint'
        },
        {
            'app': 'blueprint',
            'name': '评论管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/blueprint/comment'
        },
        {
            'app': 'blueprint',
            'name': '图片管理',
            'icon': 'fas fa-user-shield',
            'url': '/admin/blueprint/picture'
        },

        # {
        #     'app': 'master',
        #     'name': '大师管理',
        #     'icon': 'fas fa-user-shield',
        #     'url':'/admin/master/master'
        # },

    ]
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v=%=i(4g)jg@exzq430qa9ij3=*ph*1an!501c!755n!gpst&8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Tapp.apps.TappConfig',
    'api.apps.ApiConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'T.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'T.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',

        # 'NAME': "exercise",
        # 'USER': 'root',
        # 'PASSWORD': "",
        # 'HOST': "47.100.125.181"
        'NAME': "ex",
        'USER': 'root',
        'PASSWORD': "chenty73",
        'HOST': "127.0.0.1"
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# AUTH_USER_MODEL = 'Tapp.User'