# Generated by Django 2.2.3 on 2019-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=300)),
                ('state', models.IntegerField()),
                ('money', models.IntegerField()),
                ('adminid', models.IntegerField()),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
                ('addtime', models.DateField()),
                ('address', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('state', models.PositiveIntegerField()),
                ('clubid', models.IntegerField()),
            ],
            options={
                'db_table': 'cadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('clubid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=300)),
                ('state', models.PositiveIntegerField()),
                ('img', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('star', models.IntegerField(blank=True, null=True)),
                ('staruser', models.IntegerField(blank=True, null=True)),
                ('wurl', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('state', models.IntegerField()),
                ('astate', models.IntegerField()),
                ('usestate', models.IntegerField()),
                ('clubid', models.IntegerField()),
                ('introduce', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('clubid', models.IntegerField()),
                ('introduce', models.CharField(max_length=300)),
                ('state', models.IntegerField()),
                ('startdate', models.DateField()),
                ('endtime', models.DateField()),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursevideo',
            fields=[
                ('cvid', models.AutoField(primary_key=True, serialize=False)),
                ('introduce', models.CharField(max_length=300)),
                ('courseid', models.IntegerField()),
                ('video', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'coursevideo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=300)),
                ('data', models.DateTimeField()),
                ('usersid', models.CharField(max_length=300)),
                ('state', models.IntegerField()),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
                ('addtime', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('money', models.IntegerField()),
            ],
            options={
                'db_table': 'match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('mid', models.IntegerField(blank=True, null=True)),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('aid', models.IntegerField(blank=True, null=True)),
                ('ordertime', models.DateField()),
                ('other', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=180)),
                ('uid', models.IntegerField()),
                ('date', models.DateField()),
                ('times', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sadmin',
            fields=[
                ('sname', models.CharField(max_length=30)),
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('spwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signclub',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('applystate', models.IntegerField()),
                ('accessstate', models.IntegerField()),
            ],
            options={
                'db_table': 'signclub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=300)),
                ('clubid', models.IntegerField()),
                ('state', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('deadline', models.DateField()),
                ('cid', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
            options={
                'db_table': 'training',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('upwd', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=30)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('clubid', models.IntegerField()),
                ('mstate', models.IntegerField()),
                ('astate', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
